# Generated by Django 4.1.7 on 2023-09-05 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0004_ip_city_ip_latitude_ip_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="ip",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
