# Generated by Django 4.1.7 on 2023-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0005_ip_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ip",
            old_name="created_at",
            new_name="time",
        ),
        migrations.AddField(
            model_name="ip",
            name="method",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ip",
            name="page",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
