# Generated by Django 4.1.7 on 2023-10-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0007_uniqueip"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="ip2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shortner.uniqueip",
            ),
        ),
    ]
