# Generated by Django 4.1.7 on 2024-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0009_url_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureToggle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
