# Generated by Django 4.1.7 on 2023-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="ip",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
