# Generated by Django 4.1.7 on 2023-04-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0002_url_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="ip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
    ]
